[package]
name = "dkxltks25"
version = "0.1.0"
authors = ["bagjaehong <dkxltks25@naver.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
